# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        image_partner:
            quality: 85
            filters:
                scale:
                    dim: [ 200, 200 ]
        image_category:
            quality: 85
            filters:
                scale:
                    dim: [ 300, 300 ]
        image_project:
            quality: 85
            filters:
                scale:
                    dim: [ 350, 350 ]
        image_project_two:
            quality: 85
            filters:
                scale:
                    dim: [ 400, 400 ]